import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {comments} from '../../data/comments'

export default function Comment({searchComment}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>J!kMUNN - all comments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <h1>@ll comments for single post!</h1>
          <h3>{searchComment.id}. {searchComment.text}</h3>
    </div>
  )
}


export function getStaticPaths() {
    return {
        paths: [
            { params: { commentId: '1' } },
            { params: { commentId: '2' } },
            { params: { commentId: '3' } },
        ],
        fallback: false
    }
}


export function getStaticProps(context) {
    const { params } = context
    const { commentId } = params
    
    const searchComment = comments.find((comment) => comment.id === parseInt(commentId))
    console.log(searchComment)
    return {
        props: {
            searchComment
        }
    }
}
