import Head from 'next/head'
import { getSession, useSession } from 'next-auth/client'

export default function Blog({ data }) {
  const [session] = useSession()
  console.log(session)
  return (
    <div>
      <Head>
        <title>J!KMUNN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <h1>This is Blog Page- {data} </h1>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: `api/auth/signin?callbackUrl=http://localhost:3000/blog`,
        permanent: false
       }
     }
  }
  return {
    props: {
      session,
      data: session ? 'List of personalized blogs' : 'List of free blogs'
     }
  }
}
