import { getSession, signIn } from 'next-auth/client'
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function DashBoard() {
  const [loading, setLoading] = useState(true)
  
  useEffect(() => {
    const securePage = async () => {
      const session = await getSession()
      if (!session) {
        signIn()
      } else {
        setLoading(false)
      }
    }
    securePage()
  }, [])
  
  if (loading) {
     return <h1>Loading....</h1>
  }
  return (
    <div>
      <Head>
        <title>J!KMUNN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <h1>This is DashBoard Page</h1>
    </div>
  )
}
