import Head from 'next/head'
import { useSession } from 'next-auth/client'

export default function Home() {
  const [session, loading] = useSession()
  console.log({session, loading})
  return (
    <div>
      <Head>
        <title>J!KMUNN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <h1>Hi</h1>
    </div>
  )
}
